#!/usr/bin/perl
use strict;
use warnings;

print '-' x 100, "\n";
while (<>) {
    print "\033[0;32m" if (/^\+[^\+]/); # Green
    print "\033[0;31m" if (/^-[^-]/);   # Red
    print "\033[1;33m" if (/^\+\+\+/);  # Yellow
    print "\033[1;35m" if (/^---/);     # Pink
    print "\033[1;36m" if (/^@@/);      # Cyan
    print $_;
    print "\033[0m"; # Default
}
